#!/bin/sh   

echo ''
echo ''
echo '********************************************************'
echo '            INSTALL DEVICE HOOK '
echo '********************************************************'
echo ''
snap run coates-installer.configure